# .github/workflows/ci.yml
name: Base Controller CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Start Services
        # THIS ENV BLOCK IS THE FIX
        # It securely provides the credentials to Docker Compose
        env:
          WORKFLOW_DB_USER: ${{ secrets.WORKFLOW_DB_USER }}
          WORKFLOW_DB_PASSWORD: ${{ secrets.WORKFLOW_DB_PASSWORD }}
          WORKFLOW_DB_NAME: ${{ secrets.WORKFLOW_DB_NAME }}
        run: docker-compose up -d

      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test
        env:   
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: 'digicred-Test'

      - name: Stop Services
        # This 'if' statement ensures this step runs even if tests fail
        if: always()
        run: docker-compose down 
