# This is the correct and final content for .github/workflows/ci.yml

name: Base Controller CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build-and-test:
    # Using your self-hosted runner as specified in your file
    runs-on: self-hosted

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn' 

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests and Send Notification
        run: yarn test
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: 'digicred-Test'
          SLACK_MESSAGE: 'DigiCred-Holdings-Base-Controller Unit tested'
